version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: template
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "huytv"
      MYSQL_PASSWORD: "huytv"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: